### ISSUE TITLE
版本兼容更新

### ISSUE THREAD

**Issue by lpcheng1208** [jsli/NIM_API_Python#1]
![image](https://user-images.githubusercontent.com/23254534/51897493-d33f3d80-23e9-11e9-95ed-8e5a9478245a.png)

请求删除NIM_API_Python/netease_im/components/message.py 上图片的print 无实际作用但是在python3.6却无法使用

**Comment by lpcheng1208** [comment]
请求删除NIM_API_Python/netease_im/components/message.py 上图片的print 无实际作用但是在python3.6却无法使用

**Comment by jsli** [comment]
请提PR吧，谢谢
